"""persist billing calendar anchors

Revision ID: 47b6a88d1258
Revises: 20261003redact
Create Date: 2026-10-03 09:47:28.987482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b6a88d1258'
down_revision: Union[str, Sequence[str], None] = '20261003redact'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_timezone', sa.String(length=64), nullable=True, comment='IANA Billing Timezone'))
        batch_op.add_column(sa.Column('billing_anchor_day', sa.Integer(), nullable=True, comment='Original Local Billing Day'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_subscription', schema=None) as batch_op:
        batch_op.drop_column('billing_anchor_day')
        batch_op.drop_column('billing_timezone')

    # ### end Alembic commands ###
