"""initial erp schema

Revision ID: 566e9edc6fac
Revises: 
Create Date: 2026-10-03 09:28:27.503713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566e9edc6fac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_stage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Stage Name'),
    sa.Column('sequence', sa.Integer(), nullable=True, comment='Sort Sequence'),
    sa.Column('is_won', sa.Boolean(), nullable=True, comment='Is Won Stage'),
    sa.Column('is_lost', sa.Boolean(), nullable=True, comment='Is Lost Stage'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_stage'))
    )
    op.create_table('erp_outbox_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('target_service', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_outbox_event'))
    )
    with op.batch_alter_table('erp_outbox_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_outbox_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_outbox_event_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_erp_outbox_event_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_outbox_event_target_service'), ['target_service'], unique=False)

    op.create_table('ir_sequence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False, comment='Sequence Code'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Sequence Name'),
    sa.Column('prefix', sa.String(length=32), nullable=True, comment='Prefix'),
    sa.Column('padding', sa.Integer(), nullable=True, comment='Number Padding'),
    sa.Column('next_number', sa.Integer(), nullable=True, comment='Next Number'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ir_sequence')),
    sa.UniqueConstraint('code', name=op.f('uq_ir_sequence_code'))
    )
    op.create_table('product_template',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Product Name'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='Internal Reference / SKU'),
    sa.Column('kind', sa.String(length=64), nullable=False, comment='Product Kind'),
    sa.Column('list_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='Sales Price'),
    sa.Column('currency_code', sa.String(length=8), nullable=True, comment='Currency'),
    sa.Column('billing_interval', sa.String(length=64), nullable=True, comment='Billing Interval'),
    sa.Column('rate_limit', sa.String(length=64), nullable=True, comment='MikroTik Rate Limit (e.g. 50M/50M)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_template'))
    )
    with op.batch_alter_table('product_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_template_code'), ['code'], unique=False)

    op.create_table('res_company',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Company Name'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='Short Code'),
    sa.Column('currency_code', sa.String(length=8), nullable=True, comment='Base Currency'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='Email'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='Phone Number'),
    sa.Column('address', sa.Text(), nullable=True, comment='Official Address'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_res_company')),
    sa.UniqueConstraint('code', name=op.f('uq_res_company_code'))
    )
    op.create_table('res_partner',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Partner Name'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='Email Address'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='Phone / WhatsApp'),
    sa.Column('address', sa.Text(), nullable=True, comment='Full Address'),
    sa.Column('city', sa.String(length=128), nullable=True, comment='City'),
    sa.Column('is_customer', sa.Boolean(), nullable=True, comment='Is a Customer'),
    sa.Column('is_subscriber', sa.Boolean(), nullable=True, comment='Is a Broadband / Cloud Subscriber'),
    sa.Column('is_vendor', sa.Boolean(), nullable=True, comment='Is a Vendor'),
    sa.Column('radius_username', sa.String(length=64), nullable=True, comment='RADIUS / PPPoE Username'),
    sa.Column('radius_profile', sa.String(length=64), nullable=True, comment='Assigned Rate Profile'),
    sa.Column('radius_framed_ip', sa.String(length=45), nullable=True, comment='Assigned Static IP'),
    sa.Column('radius_status', sa.String(length=64), nullable=True, comment='Broadband Status'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_res_partner'))
    )
    with op.batch_alter_table('res_partner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_res_partner_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_res_partner_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_res_partner_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_res_partner_radius_username'), ['radius_username'], unique=False)

    op.create_table('crm_lead',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Opportunity Title'),
    sa.Column('partner_id', sa.String(length=36), nullable=True, comment='Customer'),
    sa.Column('contact_name', sa.String(length=128), nullable=True, comment='Contact Person'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='Email Address'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='Phone / WhatsApp'),
    sa.Column('expected_revenue', sa.Numeric(precision=20, scale=4), nullable=True, comment='Expected Revenue'),
    sa.Column('probability', sa.Integer(), nullable=True, comment='Success Probability (%)'),
    sa.Column('stage', sa.String(length=64), nullable=True, comment='Pipeline Stage'),
    sa.Column('description', sa.Text(), nullable=True, comment='Notes & Requirements'),
    sa.ForeignKeyConstraint(['partner_id'], ['res_partner.id'], name=op.f('fk_crm_lead_partner_id_res_partner'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_lead'))
    )
    with op.batch_alter_table('crm_lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_lead_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_lead_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_lead_stage'), ['stage'], unique=False)

    op.create_table('isp_nas_binding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False, comment='Customer'),
    sa.Column('nas_ip', sa.String(length=45), nullable=False, comment='Router / NAS IP'),
    sa.Column('vlan_id', sa.Integer(), nullable=True, comment='VLAN ID'),
    sa.Column('circuit_id', sa.String(length=64), nullable=True, comment='Fiber Circuit / OLT Port'),
    sa.ForeignKeyConstraint(['partner_id'], ['res_partner.id'], name=op.f('fk_isp_nas_binding_partner_id_res_partner'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_isp_nas_binding'))
    )
    with op.batch_alter_table('isp_nas_binding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_isp_nas_binding_partner_id'), ['partner_id'], unique=False)

    op.create_table('sale_order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False, comment='Order Number'),
    sa.Column('partner_id', sa.String(length=36), nullable=False, comment='Customer'),
    sa.Column('state', sa.String(length=64), nullable=True, comment='Order Status'),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True, comment='Order Date'),
    sa.Column('currency_code', sa.String(length=8), nullable=True, comment='Currency'),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=4), nullable=True, comment='Total Amount'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Terms & Conditions'),
    sa.ForeignKeyConstraint(['partner_id'], ['res_partner.id'], name=op.f('fk_sale_order_partner_id_res_partner'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_order'))
    )
    with op.batch_alter_table('sale_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_order_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sale_order_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_order_state'), ['state'], unique=False)

    op.create_table('sale_order_line',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False, comment='Order Reference'),
    sa.Column('product_id', sa.String(length=36), nullable=True, comment='Product'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Description'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True, comment='Quantity'),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='Unit Price'),
    sa.Column('subtotal', sa.Numeric(precision=20, scale=4), nullable=True, comment='Subtotal'),
    sa.Column('line_kind', sa.String(length=64), nullable=True, comment='Line Kind'),
    sa.ForeignKeyConstraint(['order_id'], ['sale_order.id'], name=op.f('fk_sale_order_line_order_id_sale_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product_template.id'], name=op.f('fk_sale_order_line_product_id_product_template'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_order_line'))
    )
    with op.batch_alter_table('sale_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_order_line_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_order_line_product_id'), ['product_id'], unique=False)

    op.create_table('sale_subscription',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False, comment='Subscription Number'),
    sa.Column('partner_id', sa.String(length=36), nullable=False, comment='Subscriber / Customer'),
    sa.Column('source_order_id', sa.String(length=36), nullable=True, comment='Source Sales Order'),
    sa.Column('state', sa.String(length=64), nullable=True, comment='Subscription State'),
    sa.Column('currency_code', sa.String(length=8), nullable=True, comment='Currency'),
    sa.Column('mrr', sa.Numeric(precision=20, scale=4), nullable=True, comment='Monthly Recurring Revenue (MRR)'),
    sa.Column('billing_interval', sa.String(length=64), nullable=True, comment='Billing Interval'),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True, comment='Current Period Start'),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True, comment='Current Period End'),
    sa.Column('next_invoice_at', sa.DateTime(timezone=True), nullable=True, comment='Next Invoice Date'),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True, comment='Grace Deadline'),
    sa.Column('technical_service', sa.String(length=64), nullable=True, comment='Technical Service Type'),
    sa.Column('technical_reference', sa.String(length=128), nullable=True, comment='Technical Identifier (PPPoE User / Container ID)'),
    sa.Column('technical_profile', sa.String(length=64), nullable=True, comment='Technical Profile / Rate Limit'),
    sa.ForeignKeyConstraint(['partner_id'], ['res_partner.id'], name=op.f('fk_sale_subscription_partner_id_res_partner'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_order_id'], ['sale_order.id'], name=op.f('fk_sale_subscription_source_order_id_sale_order'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_subscription'))
    )
    with op.batch_alter_table('sale_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_subscription_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sale_subscription_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_subscription_source_order_id'), ['source_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_subscription_state'), ['state'], unique=False)

    op.create_table('account_move',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False, comment='Invoice Number'),
    sa.Column('partner_id', sa.String(length=36), nullable=False, comment='Customer'),
    sa.Column('source_order_id', sa.String(length=36), nullable=True, comment='Originating Sales Order'),
    sa.Column('subscription_id', sa.String(length=36), nullable=True, comment='Originating Subscription'),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True, comment='Invoice Date'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='Payment Due Date'),
    sa.Column('currency_code', sa.String(length=8), nullable=True, comment='Currency'),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=4), nullable=True, comment='Total Due'),
    sa.Column('state', sa.String(length=64), nullable=True, comment='Invoice Status'),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True, comment='Payment Timestamp'),
    sa.Column('payment_method', sa.String(length=64), nullable=True, comment='Payment Method (e.g. Bank Transfer, Gateway)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Payment Instructions'),
    sa.ForeignKeyConstraint(['partner_id'], ['res_partner.id'], name=op.f('fk_account_move_partner_id_res_partner'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_order_id'], ['sale_order.id'], name=op.f('fk_account_move_source_order_id_sale_order'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['sale_subscription.id'], name=op.f('fk_account_move_subscription_id_sale_subscription'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_move'))
    )
    with op.batch_alter_table('account_move', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_move_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_account_move_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_move_source_order_id'), ['source_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_move_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_move_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('project_project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Project / Workload Name'),
    sa.Column('partner_id', sa.String(length=36), nullable=False, comment='Client / Customer'),
    sa.Column('subscription_id', sa.String(length=36), nullable=True, comment='Linked Subscription'),
    sa.Column('runner_workload_id', sa.String(length=128), nullable=True, comment='Runner Workload / Container ID'),
    sa.Column('runner_deploy_mode', sa.String(length=64), nullable=True, comment='Deployment Mode'),
    sa.Column('status', sa.String(length=64), nullable=True, comment='Workload Status'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Technical Specifications & Notes'),
    sa.ForeignKeyConstraint(['partner_id'], ['res_partner.id'], name=op.f('fk_project_project_partner_id_res_partner'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['sale_subscription.id'], name=op.f('fk_project_project_subscription_id_sale_subscription'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_project'))
    )
    with op.batch_alter_table('project_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_project_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_project_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_project_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('subscription_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False, comment='Subscription'),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='Event Type'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True, comment='Event Timestamp'),
    sa.Column('note', sa.Text(), nullable=True, comment='Event Details / Actor / Reason'),
    sa.ForeignKeyConstraint(['subscription_id'], ['sale_subscription.id'], name=op.f('fk_subscription_event_subscription_id_sale_subscription'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_event'))
    )
    with op.batch_alter_table('subscription_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_event_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('subscription_line',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False, comment='Subscription'),
    sa.Column('product_id', sa.String(length=36), nullable=True, comment='Service Product'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Description'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True, comment='Quantity'),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='Recurring Rate'),
    sa.Column('subtotal', sa.Numeric(precision=20, scale=4), nullable=True, comment='Subtotal'),
    sa.ForeignKeyConstraint(['product_id'], ['product_template.id'], name=op.f('fk_subscription_line_product_id_product_template'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['sale_subscription.id'], name=op.f('fk_subscription_line_subscription_id_sale_subscription'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_line'))
    )
    with op.batch_alter_table('subscription_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_line_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_line_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('account_move_line',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('move_id', sa.String(length=36), nullable=False, comment='Invoice Reference'),
    sa.Column('product_id', sa.String(length=36), nullable=True, comment='Billed Product'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Description'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True, comment='Quantity'),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='Unit Price'),
    sa.Column('subtotal', sa.Numeric(precision=20, scale=4), nullable=True, comment='Line Subtotal'),
    sa.ForeignKeyConstraint(['move_id'], ['account_move.id'], name=op.f('fk_account_move_line_move_id_account_move'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product_template.id'], name=op.f('fk_account_move_line_product_id_product_template'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_move_line'))
    )
    with op.batch_alter_table('account_move_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_move_line_move_id'), ['move_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_move_line_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_move_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_move_line_product_id'))
        batch_op.drop_index(batch_op.f('ix_account_move_line_move_id'))

    op.drop_table('account_move_line')
    with op.batch_alter_table('subscription_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_line_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_line_product_id'))

    op.drop_table('subscription_line')
    with op.batch_alter_table('subscription_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_event_subscription_id'))

    op.drop_table('subscription_event')
    with op.batch_alter_table('project_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_project_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_project_project_status'))
        batch_op.drop_index(batch_op.f('ix_project_project_partner_id'))

    op.drop_table('project_project')
    with op.batch_alter_table('account_move', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_move_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_account_move_state'))
        batch_op.drop_index(batch_op.f('ix_account_move_source_order_id'))
        batch_op.drop_index(batch_op.f('ix_account_move_partner_id'))
        batch_op.drop_index(batch_op.f('ix_account_move_number'))

    op.drop_table('account_move')
    with op.batch_alter_table('sale_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_subscription_state'))
        batch_op.drop_index(batch_op.f('ix_sale_subscription_source_order_id'))
        batch_op.drop_index(batch_op.f('ix_sale_subscription_partner_id'))
        batch_op.drop_index(batch_op.f('ix_sale_subscription_number'))

    op.drop_table('sale_subscription')
    with op.batch_alter_table('sale_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_order_line_product_id'))
        batch_op.drop_index(batch_op.f('ix_sale_order_line_order_id'))

    op.drop_table('sale_order_line')
    with op.batch_alter_table('sale_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_order_state'))
        batch_op.drop_index(batch_op.f('ix_sale_order_partner_id'))
        batch_op.drop_index(batch_op.f('ix_sale_order_number'))

    op.drop_table('sale_order')
    with op.batch_alter_table('isp_nas_binding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_isp_nas_binding_partner_id'))

    op.drop_table('isp_nas_binding')
    with op.batch_alter_table('crm_lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_lead_stage'))
        batch_op.drop_index(batch_op.f('ix_crm_lead_partner_id'))
        batch_op.drop_index(batch_op.f('ix_crm_lead_name'))

    op.drop_table('crm_lead')
    with op.batch_alter_table('res_partner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_res_partner_radius_username'))
        batch_op.drop_index(batch_op.f('ix_res_partner_phone'))
        batch_op.drop_index(batch_op.f('ix_res_partner_name'))
        batch_op.drop_index(batch_op.f('ix_res_partner_email'))

    op.drop_table('res_partner')
    op.drop_table('res_company')
    with op.batch_alter_table('product_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_template_code'))

    op.drop_table('product_template')
    op.drop_table('ir_sequence')
    with op.batch_alter_table('erp_outbox_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_outbox_event_target_service'))
        batch_op.drop_index(batch_op.f('ix_erp_outbox_event_status'))
        batch_op.drop_index(batch_op.f('ix_erp_outbox_event_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_erp_outbox_event_event_type'))

    op.drop_table('erp_outbox_event')
    op.drop_table('crm_stage')
    # ### end Alembic commands ###
