"""encrypted credentials and outbox leases

Revision ID: 72682e2e996c
Revises: 566e9edc6fac
Create Date: 2026-10-03 09:37:49.254523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72682e2e996c'
down_revision: Union[str, Sequence[str], None] = '566e9edc6fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_outbox_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_erp_outbox_event_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_outbox_event_lease_token'), ['lease_token'], unique=False)

    with op.batch_alter_table('res_partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radius_credential_ciphertext', sa.String(length=512), nullable=True, comment='Encrypted RADIUS credential'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('res_partner', schema=None) as batch_op:
        batch_op.drop_column('radius_credential_ciphertext')

    with op.batch_alter_table('erp_outbox_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_outbox_event_lease_token'))
        batch_op.drop_index(batch_op.f('ix_erp_outbox_event_lease_expires_at'))
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('lease_token')

    # ### end Alembic commands ###
